// Outbound email send via the Cloudflare Email Service binding (env.EMAIL).
// Uses the modern structured send() API — see workers/email-sender.ts for
// the canonical pattern. On paid plans this delivers to arbitrary
// recipients; on free plans only to verified Email Routing destinations.
// The HMAC-signed Reply-To encodes (mission, thread, target) so inbound
// replies route back to the right MissionDO.

import type { Env } from "../../types";
import type { MissionDO } from "../mission-do";
import { DEFAULT_USER_ID } from "../index";
import { recordInteraction } from "./contact-ingest";
import { signReplyToken } from "./hmac";

export interface SendEmailInput {
	missionId: string;
	threadId: string;
	from: string;
	to: string;
	cc?: string;
	subject: string;
	body: string;
	agentId: string;
	targetId?: string;
}

export interface SendEmailResult {
	messageId: string;
	replyTo: string;
	delivered: boolean;
	error?: string; // populated when delivered=false to explain why
}

export async function sendEmail(
	env: Env,
	mdo: MissionDO,
	input: SendEmailInput,
): Promise<SendEmailResult> {
	const messageId = `<${crypto.randomUUID()}@${domainFromEmail(input.from)}>`;
	const replyTo = await buildReplyTo(env, input);

	// Persist the outbound message row.
	await mdo.addMessage({
		thread_id: input.threadId,
		direction: "out",
		from_addr: input.from,
		to_addr: input.to,
		cc: input.cc ?? null,
		subject: input.subject,
		body: input.body,
		sent_at: new Date().toISOString(),
		message_id: messageId,
		in_reply_to: null,
	});

	// Record the interaction in the cross-mission Contact log. This is the
	// non-negotiable step — see docs/missions-prd.md § Contacts.
	await recordInteraction(env, {
		userId: DEFAULT_USER_ID,
		agentId: input.agentId,
		missionId: input.missionId,
		email: input.to,
		type: "email_sent",
		summary: input.subject,
		metadata: { thread_id: input.threadId, message_id: messageId },
	});

	// Delivery via the Cloudflare Email Service binding.
	let delivered = false;
	let error: string | undefined;
	try {
		delivered = await deliverViaBinding(env, {
			from: input.from,
			to: input.to,
			cc: input.cc,
			subject: input.subject,
			body: input.body,
			messageId,
			replyTo,
		});
		if (!delivered) error = "EMAIL binding not present on env";
	} catch (err) {
		const message = (err as Error).message ?? String(err);
		console.warn(
			`[email-out] delivery failed for ${input.to}:`,
			message,
		);
		delivered = false;
		error = message;
	}

	return { messageId, replyTo, delivered, error };
}

function domainFromEmail(email: string): string {
	const at = email.indexOf("@");
	return at >= 0 ? email.slice(at + 1) : "invalid";
}

async function buildReplyTo(env: Env, input: SendEmailInput): Promise<string> {
	// HMAC-signed token encodes (mission_id, thread_id, target_id) so inbound
	// replies route back to the right MissionDO regardless of the recipient.
	const token = await signReplyToken(env, {
		missionId: input.missionId,
		threadId: input.threadId,
		targetId: input.targetId ?? null,
	});
	const domain = domainFromEmail(input.from);
	return `reply+${token}@${domain}`;
}

// ── Delivery via the Cloudflare Email Service binding ───────────────
// Uses the modern structured send() API. See workers/email-sender.ts
// for the canonical helper.

interface DeliverInput {
	from: string;
	to: string;
	cc?: string;
	subject: string;
	body: string;
	messageId: string;
	replyTo: string;
}

async function deliverViaBinding(env: Env, d: DeliverInput): Promise<boolean> {
	if (!env.EMAIL) {
		// Binding absent — treat as logged-only (local dev without miniflare
		// email emulation, or a misconfigured deploy).
		return false;
	}

	// CF Email Service whitelists headers — Message-ID is generated by CF,
	// we don't set it. Reply routing uses the HMAC-signed Reply-To token,
	// not RFC 5322 threading headers, so this has no functional cost.
	await env.EMAIL.send({
		to: d.to,
		from: d.from,
		subject: d.subject,
		text: d.body,
		cc: d.cc,
		replyTo: d.replyTo,
	} as Parameters<SendEmail["send"]>[0]);
	return true;
}
