// Copyright (c) 2026 Cloudflare, Inc.
// Licensed under the Apache 2.0 license found in the LICENSE file or at:
//     https://opensource.org/licenses/Apache-2.0

// Env is generated by `wrangler types` from wrangler.jsonc bindings and
// .dev.vars — see worker-configuration.d.ts. We re-export the ambient
// Cloudflare.Env as our Env so call sites don't need two imports.
//
// Secrets surfaced here:
//   ANTHROPIC_API_KEY — Claude drafting (required)
//   HMAC_SECRET       — signs Reply-To tokens + guards the inbound webhook
//   RESEND_API_KEY    — outbound via Resend (recommended for cold outreach)
export type Env = Cloudflare.Env;
